### ISSUE TITLE
What changes are required if the Gitlab URL is custom and requires tls certificate

### ISSUE THREAD

**Issue by jkjoshi1** [aws-samples/cdk-fargate-gitlab-runner#11]
I am using this code for setting up a scalable runner. My gitlab URL is not default and requires a certificate. I have managed to put certificate in the docker. Although the POST request throws a 400 error on hitting the endpoint. What changes does in this code could fix it?

**Comment by boooziz** [comment]
Hello @jkjoshi1 ,
First you set the gitlab server in [app.yml](https://github.com/aws-samples/cdk-fargate-gitlab-runner/blob/main/config/app.yml-example).
For the custom certificate, did you try to add them to the [fargate driver]( https://github.com/aws-samples/cdk-fargate-gitlab-runner/blob/main/gitlab_ci_fargate_runner/docker_fargate_driver/Dockerfile) that runs the gitlba runner service ?
