### ISSUE TITLE
The security token included in the request is expired

### ISSUE THREAD

**Issue by plpatankar** [aws-samples/cdk-fargate-gitlab-runner#15]
I setup runner and it was working when I tested, however after some days when new job is trigged using gitlab pipeline following error has occurred. Looks like ECS security credentials generated for the task has expired. 
Reinstalling the runner again solves the issue. Do we have any option so that runner credentials will stay active even there are no job scheduled for some days and it can resume back when there is new job in pipeline ? 

`"starting new Fargate task: running new task on Fargate: error starting AWS Fargate Task: ExpiredTokenException: The security token included in the request is expired\n\tstatus code: 400, request id: 4b855cc3-e596-4cf9-9c40-f7bad2478685"`

**Comment by boooziz** [comment]
Hello  [plpatankar](https://github.com/plpatankar)
I can't reproduce the issue right now. I will wait one or two days to reproduce and get the log to try to troubleshoot it.

**Comment by boooziz** [comment]
Hello [plpatankar](https://github.com/plpatankar)
I corrected the issue and pushed a new version, please check and let me know if it works for you.
Regards

**Comment by plpatankar** [comment]
Thanks for fixing this !!
