### ISSUE TITLE
indicate token secret structure

### ISSUE THREAD

**Issue by melouaer** [aws-samples/cdk-fargate-gitlab-runner#6]
In the readme we are asked to create a secret in secrets manager in order to store gitlab token.
The readme does not indicate that the key of the secret should be "token" and the value the token itself

**Comment by boooziz** [comment]
Ok, i will update the documentation and push a new release

**Comment by boooziz** [comment]
Modification merged https://github.com/aws-samples/cdk-fargate-gitlab-runner/pull/7
