### ISSUE TITLE
Unable to satisfy 100% MinSuccessfulInstancesPercent requirement

### ISSUE THREAD

**Issue by danielbayerlein** [aws-samples/cdk-fargate-gitlab-runner#9]
I get the following error when deploying:

```
16:21:37 | CREATE_IN_PROGRESS   | AWS::CloudFormation::Stack            | GitlabrunnerBastionStack
16:29:52 | CREATE_FAILED        | AWS::AutoScaling::AutoScalingGroup    | GitlabrunnerAsg1bASG63ACEABF
Received 0 SUCCESS signal(s) out of 1.  Unable to satisfy 100% MinSuccessfulInstancesPercent requirement
```

**Comment by boooziz** [comment]
Hello Daniel,
ThIs error indicates  that there were an error in cfn-init when installing  gitlab runner bastion. Can you check the network configuration? The subnet where the bastion is deployed should have internet out access and also https  access to the gilab host.

**Comment by boooziz** [comment]
Hello Daniel,
A new version published yesterday which is full serveless, no need now to ec2 instance , all run with fargate.
